import { useState } from 'react';
import { money, shortDate } from '../finance.js';
import { buildCurrentReport, currentMonthInLima, monthLabel } from '../monthlyReports.js';
import EvolutionChart from './EvolutionChart.jsx';
import { Icon } from './Identity.jsx';
const amount = value => value == null ? 'Sin datos' : money(value);
export default function ReportsView({ data, selectedMonth, onSelectMonth, history }) {
  const [tab,setTab] = useState('trend');
  const current = currentMonthInLima();
  const report = selectedMonth===current ? buildCurrentReport(data,current) : history.reports.find(r=>r.month.slice(0,7)===selectedMonth);
  const closed = Boolean(report?.closed_at);
  function select(month) { onSelectMonth(month); setTab('history'); }
  return <div className="view-stack"><div className="page-intro"><h1>Cada mes cuenta.</h1><p>Tu evolución financiera, con cierres automáticos en la hora de Perú.</p></div><div className="segmented page-tabs"><button aria-pressed={tab==='trend'} onClick={()=>setTab('trend')}>Evolución</button><button aria-pressed={tab==='history'} onClick={()=>setTab('history')}>Cierres mensuales</button></div>
    {tab==='trend'&&<EvolutionChart {...history} onSelectMonth={select}/>}
    <section className="surface"><div className="section-heading"><div><span className="eyebrow">Reporte mensual</span><h2 className="capitalize">{monthLabel(selectedMonth)}</h2></div><span className={`status-pill ${closed?'':'pending'}`}><Icon name={closed?'lock':'evolution'} size={13}/>{closed?'Cerrado':selectedMonth===current?'En curso':selectedMonth>current?'Mes futuro':'Cierre pendiente'}</span></div>
      {history.error&&<div className="notice" role="alert">{history.error}<button className="text-action" onClick={history.retry}>Volver a intentar</button></div>}
      {report?<><div className="report-stats">{[['Ingresos',report.income],['Gastos',report.expenses],['Saldo del mes',report.cash_flow],['Balance acumulado',report.accumulated_balance],['Deuda pendiente',report.debt],['Inversiones',report.investments],['Patrimonio estimado',report.net_worth]].map(([label,value])=><div key={label}><span>{label}</span><strong className={value<0?'danger':''}>{amount(value)}</strong></div>)}<div><span>Saldo / ingresos</span><strong>{report.savings_rate==null?'Sin ingresos':`${Number(report.savings_rate).toFixed(1)}%`}</strong></div></div><p className="fine-print">{closed?'Este cierre conserva sus cifras. Los ajustes posteriores se registran en el mes actual.':'Vista provisional del mes. Se actualiza con tus registros hasta el cierre.'}</p>{!report.debt_history_available&&<p className="fine-print">Este mes es anterior al historial de deudas: deuda y patrimonio no se pueden reconstruir con certeza.</p>}<details className="calculation-details"><summary>Cómo se calculan estas cifras</summary><p>El patrimonio estimado es el balance acumulado más inversiones menos deuda. El balance acumulado incluye los ingresos y gastos registrados hasta este mes.</p><p>{report.statement_date?`Último estado de inversiones al ${shortDate(report.statement_date)}.`:'Sin estado de inversiones para este mes.'} Deudas e inversiones en USD se estiman a S/3,75; los movimientos usan su tipo de cambio registrado.</p></details></>:<p className="empty-state">{history.loading?'Cargando tus reportes…':selectedMonth>current?'El reporte estará disponible cuando comience este mes.':'Todavía no hay un cierre disponible para este mes. El sistema recupera cierres pendientes automáticamente.'}</p>}
    </section>
    {tab==='history'&&<section className="surface"><div className="section-heading"><h2>Historial de cierres</h2><span className="muted">{history.reports.length} meses</span></div>{history.reports.length?<div className="report-history">{history.reports.map(r=><button key={r.month} className={`history-row ${selectedMonth===r.month.slice(0,7)?'is-selected':''}`} onClick={()=>onSelectMonth(r.month.slice(0,7))} aria-label={`Ver reporte de ${monthLabel(r.month)}`}><span><strong className="capitalize">{monthLabel(r.month)}</strong><small>Ingresos {amount(r.income)} · Gastos {amount(r.expenses)}</small></span><span><small>Saldo del mes</small><strong className={r.cash_flow<0?'danger':'positive'}>{amount(r.cash_flow)}</strong></span><Icon name="right" size={16}/></button>)}</div>:<p className="empty-state">Tu primer cierre aparecerá aquí al terminar el mes.</p>}</section>}
  </div>;
}
